### ISSUE TITLE
Data contains bruteforced wildcard domains?

### ISSUE THREAD

**Issue by uBadRequest** [g147/kenzerdb#1]
My github subdomain scanner was picking up a lot of junk subdomains and it appeared to come from this repo.

It appears that alot of the data is the result of bruteforcing. Do you not filter for wildcards?

**Comment by g147** [comment]
i did noticed that. this was generated atleast a month ago & pushed maybe 10 days ago. i don't update it usually. i didn't automate it properly the first time & yeah it contains lots of wildcards. they'll be removed someday. maybe.
